
spring.datasource.url= jdbc:postgresql://localhost:5432/rebumk
spring.datasource.username=postgres
spring.datasource.password=mete5

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto= update

flyway.user=postgres
flyway.password=mete5
flyway.schemas=uber_monolith
flyway.url=jdbc:postgresql://localhost:5432/rebumk
flyway.locations=filesystem:db/migration