spring.datasource.url= jdbc:postgresql://localhost:9999/db_202223z_va_prj_rebumk
spring.datasource.schema=project
spring.datasource.username=db_202223z_va_prj_rebumk_owner
spring.datasource.password=6e4cf730addb
spring.jpa.properties.hibernate.default_schema=project 

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= validate